### ISSUE TITLE
Root repository denied to install github hook

### ISSUE THREAD

**Issue by wjn** [nextbigsoundinc/Sprintly-GitHub#32]
```sprintly --install-hook
ERROR:__main__:Fatal Error: 'This command can only be run from the root of a git repository.'
Traceback (most recent call last):
  File "/usr/local/bin/sprintly", line 136, in run
    self.installHook()
  File "/usr/local/bin/sprintly", line 590, in installHook
    raise SprintlyException('This command can only be run from the root of a git repository.')
SprintlyException: 'This command can only be run from the root of a git repository.'
Program exiting.```

I'm in the repo's root dir. This error is being generated. Would like to use the hook but don't know how to go forward.

**Comment by F1LT3R** [comment]
Probably your hooks directory has been deleted.
Perhaps it is part of the way you have your repo configured. (Deploy hooks, etc)

Try:

```shell
mkdir .git/hooks
sprintly --install-hook
```

**Comment by justinabrahms** [comment]
Alternatively, can you provide the output of `tree` in your repo root? Specifically interested in the .git repo.
